### ISSUE TITLE
ModuleNotFoundError: No module named 'pretrainedmodels' when loading the trained quality assessment model seresnext101_6x6_all.pth

### ISSUE THREAD

**Issue by YuhuiMa** [shanzha09/COIPS#1]
Traceback (most recent call last):
  File "COIP_system.py", line 15, in <module>
    quality_assessment.main(logger)
  File "/media/yhma-imed/SDD5_930GB/MaYuhui/MyResearch/code/COIPS/quality_assessment.py", line 115, in main
    inference(logger, size=img_size)
  File "/media/yhma-imed/SDD5_930GB/MaYuhui/MyResearch/code/COIPS/quality_assessment.py", line 46, in inference
    model = torch.load(model_path, map_location='cpu')
  File "/home/yhma/anaconda3/envs/wxg_nn/lib/python3.8/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/yhma/anaconda3/envs/wxg_nn/lib/python3.8/site-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/home/yhma/anaconda3/envs/wxg_nn/lib/python3.8/site-packages/torch/serialization.py", line 1042, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'pretrainedmodels'

This error occurs when I run: 
python COIP_system.py
How can I solve the above problem?

**Comment by shanzha09** [comment]
@YuhuiMa Please download the "model dict" and retry. [https://zenodo.org/records/5111976](https://zenodo.org/records/5111976). 
![image](https://github.com/shanzha09/COIPS/assets/5896410/e5b4b8fb-b493-4507-bb05-c1068aee9f9d)

**Comment by YuhuiMa** [comment]
I have downloaded many times and there are no problems about unpacking the files. I have also checked that the path setting is correct. Could you provide the detailed information of the model by running the following code? I want to know what went wrong. 

import torch
model = torch.load("models_dict/quality_assessment/seresnext101_6x6_all.pth", map_location='cpu')
print(model)

**Comment by shanzha9** [comment]
@YuhuiMa Please run `pip install pretrainedmodels` and retry.

**Comment by YuhuiMa** [comment]
OK, it works. Thanks!
